Define a way for the CG to perform community-focused tasks on behalf of the WG
patcg/patcg.github.io pull request #12
Opened 2022-03-31 21:55 UTC by AramZS

This PR aims to define the CG's role in publicizing potential WG changes to documents on the standards track. Here we define a method by which the WG might activate this process, a process to create a venue for feedback and options on how to expand the contact to a broad set of stakeholders outside of the regular participants in this group. Finally it defines a way to examine feedback from a broader group, document it and deliver it to the WG. 

I dunno if we needed to specify sending a Tweet about it, but I figure I can put it in here and take it out if the feedback from those more experienced with writing these types of documents is that we don't need to make it explicit here. 

This change is a compliment to the proposed PR at https://github.com/patcg/patwg-charter/pull/14

2022-03-31 22:49 UTC, martinthomson requested changes
This contains far too much of the *CG* process.

I think that what you want is much simpler.  

> At any time, but always when a specification is undergoing a state change, the WG will ask the CG for feedback.  The WG will allow the CG at least a month (4 weeks?) to gather that feedback.

That is all; how the feedback is requested is CG business.  How the CG then gathers that feedback is their business.

2022-03-31 23:28 UTC, AramZS commented
@martinthomson That sounds fine to me, edits made along those lines.

2022-03-31 23:39 UTC, martinthomson approved these changes

2022-03-31 23:39 UTC, martinthomson commented on charter.html
> +ask the CG for feedback. The WG will allow the CG at least 4 weeks to gather
```suggestion
ask <a href="https://patcg.github.io/">PATCG</a> for feedback. The WG will allow the CG at least 4 weeks to gather
```

2022-04-01 12:33 UTC, bslassey commented
This text looks good to me.

2022-04-07 15:19 UTC, ekr commented
I can live with this.

2022-04-07 15:32 UTC, merged